### ISSUE TITLE
Comment modifier les thèmes des pages profil ? 

### ISSUE THREAD

**Issue by laem** [fabmob/wiki#11]
Savez-vous pourquoi [cette page](https://wiki.lafabriquedesmobilites.fr/index.php?title=Attribut:Theme&action=edit) qui semble être l'endroit où l'on édite le champ "Theme" du profil utilisateur [ici](https://wiki.lafabriquedesmobilites.fr/index.php?title=Mod%C3%A8le:User&action=edit), les thèmes ne correspondent pas à ceux qu'on voit quand on modifie son profil ?

**Comment by laem** [comment]
A priori cette page thèmes définit ceux des formulaires Projet, Commun, etc, ... pour les profils utilisateurs, c'est ailleurs

**Comment by GabrielPlassat** [comment]
En effet, il y a les thèmes des fiches acteurs, commun, projet, etc... et les thèmes utilisés dans le profil utilisateur. Ce n'est pas la même donnée. Il faudrait en parler avec Wiki Valley (nicolas)

**Comment by SimonSarazin** [comment]
Bonjour, voici une petite explication pour éditer les thèmes. A chaque modification de thème, il faut les modifier dans 3 endroits différents : 
https://wiki.lafabriquedesmobilites.fr/wiki/Le_coin_des_contributeurs#Il_y_a_ensuite_l.27espace_des_th.C3.A8mes_dans_le_profil

Il est peut-être possible d'aller chercher directement dans la propriété. Cela serait à tester prochainement  (voir dans l'aide de cette page https://github.com/Wikifab/mediawiki-extensions-wfSocialProfil )
