### ISSUE TITLE
Mise à jour à la dernière version de MediaWiki

### ISSUE THREAD

**Issue by laem** [fabmob/wiki#14]
Nous sommes à la 1.30.0, la dernière est la 1.34. 
Y a-t-il des améliorations / corrections de bug qui en font une MAJ prioritaire ?
https://wiki.lafabriquedesmobilites.fr/wiki/Sp%C3%A9cial:Version

**Comment by laem** [comment]
La LTS 1.35 est sortie. Il faudrait qu'on y passe.

Apparemment, avec l'explorer de dokit, one a des soucis avec les version plus récentes que 1.31.1, faut encore fouiller le problème.

Il faut qu'on pose la question à Dokit, et s'il faut un gros boulot pour le rendre compatible.

**Comment by GabrielPlassat** [comment]
Le wiki a été passé en 1.31.3 le 23 juin 2021

**Comment by bndn** [comment]
Le wiki a été mis à jour en 1.35 le 10 février 2022
