### ISSUE TITLE
Améliorer design pour l'ajout des compétences

### ISSUE THREAD

**Issue by SimonSarazin** [fabmob/wiki#28]

**Comment by SimonSarazin** [comment]
![image](https://user-images.githubusercontent.com/620174/153476264-cacbc1c6-4572-4648-9957-04273dcce1fb.png)

**Comment by SimonSarazin** [comment]
En fait, l'info s'affiche aussi une fois le formulaire validé, dans le profil.. donc la solution ne convient pas . A creuser

**Comment by SimonSarazin** [comment]
C'est ce champ qui est à travailler https://wiki.lafabriquedesmobilites.fr/wiki/MediaWiki:Custom-info-field13

**Comment by bndn** [comment]
@GabrielPlassat @SimonSarazin J’ai tenté d’améliorer ça. Vous me direz ce que vous en pensez. La description se modifie sur cette page https://wiki.lafabriquedesmobilites.fr/wiki/MediaWiki:Custom-info-field13-desc
![Screenshot 2022-03-07 at 09-51-31 Modifier votre profil — Communauté de la Fabrique des Mobilites](https://user-images.githubusercontent.com/1180345/156998970-61294fe8-1fe4-4690-b8f1-c6bc8e575328.png)

**Comment by GabrielPlassat** [comment]
c'est mieux en effet !
